import React, { useState } from "react";
import "./MoodSpace.css";

function MoodSpace() {
  const [user, setUser] = useState(null);
  const [loginEmail, setLoginEmail] = useState("");
  const [loginPassword, setLoginPassword] = useState("");
  const [signupName, setSignupName] = useState("");
  const [signupEmail, setSignupEmail] = useState("");
  const [signupPassword, setSignupPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");

  const handleLogin = () => {
    if (validateLogin(loginEmail, loginPassword)) {
      setUser({ name: loginEmail.split("@")[0], email: loginEmail });
    } else {
      alert("Invalid login credentials");
    }
  };

  const handleSignup = () => {
    if (
      validateSignup(signupName, signupEmail, signupPassword, confirmPassword)
    ) {
      setUser({ name: signupName, email: signupEmail });
    } else {
      alert("Please fill in all fields correctly.");
    }
  };

  const validateLogin = (email, password) => {
    return email.trim() !== "" && password.trim() !== "";
  };

  const validateSignup = (name, email, password, confirmPassword) => {
    return (
      name.trim() !== "" && email.trim() !== "" && password === confirmPassword
    );
  };

  const handleLogout = () => {
    setUser(null);
    setLoginEmail("");
    setLoginPassword("");
    setSignupName("");
    setSignupEmail("");
    setSignupPassword("");
    setConfirmPassword("");
  };

  // Main MoodSpace Page Component without className="dashboard"
  const MainPage = () => (
    <div>
      <div className="stars-background" />

      <header className="nav-header">
        <h1 className="logo">MoodSpace</h1>
        <nav className="nav-buttons">
          <button className="nav-btn">🏠 HOME</button>
          <button className="nav-btn">📊 SEGMENT</button>
          <button className="nav-btn">👤 ACCOUNT</button>
          <button className="nav-btn" onClick={handleLogout}>
            ⚙️ LOGOUT
          </button>
        </nav>
      </header>

      <main className="main-content">
        <div className="left-side">
          <div className="astronaut">
            <div className="helmet" />
            <div className="body" />
          </div>
          <div className="alien">
            <div className="eye left-eye" />
            <div className="eye right-eye" />
          </div>
        </div>

        <div className="center-planet">
          <div className="planet">
            <div className="planet-detail top-left" />
            <div className="planet-detail bottom-right" />
          </div>
        </div>

        <div className="right-side">
          <h2 className="section-title">What is MoodSpace?</h2>
          <p className="welcome-text">
            Welcome back, <strong>{user?.name}</strong>!
          </p>
          <p className="description-text">
            Moodspace is a fun and welcoming website created by five students
            for relaxation and community, featuring an AI buddy for personalized
            activity suggestions, autogenerated playlists based on your mood, a
            book therapist bot to chat with your favorite characters, movie
            options, daily affirmations, and a journaling section with creative
            prompts to spark your inspiration all while promoting mental health
            awareness and support!
          </p>
        </div>
      </main>
    </div>
  );

  return (
    <div className="app-container">
      <h1>Welcome to MoodSpace</h1>
      {!user ? (
        <div className="auth-page">
          <h2>Login / Sign Up</h2>
          <div className="auth-section">
            <input
              type="email"
              className="form-input"
              placeholder="Enter email"
              value={loginEmail}
              onChange={(e) => setLoginEmail(e.target.value)}
            />
            <input
              type="password"
              className="form-input"
              placeholder="Enter password"
              value={loginPassword}
              onChange={(e) => setLoginPassword(e.target.value)}
            />
            <button className="btn-primary" onClick={handleLogin}>
              Login
            </button>
          </div>
          <div className="auth-section">
            <input
              type="text"
              className="form-input"
              placeholder="Enter name"
              value={signupName}
              onChange={(e) => setSignupName(e.target.value)}
            />
            <input
              type="email"
              className="form-input"
              placeholder="Enter email"
              value={signupEmail}
              onChange={(e) => setSignupEmail(e.target.value)}
            />
            <input
              type="password"
              className="form-input"
              placeholder="Enter password"
              value={signupPassword}
              onChange={(e) => setSignupPassword(e.target.value)}
            />
            <input
              type="password"
              className="form-input"
              placeholder="Confirm password"
              value={confirmPassword}
              onChange={(e) => setConfirmPassword(e.target.value)}
            />
            <button className="btn-primary" onClick={handleSignup}>
              Sign Up
            </button>
          </div>
        </div>
      ) : (
        <MainPage />
      )}
    </div>
  );
}

export default MoodSpace;
